deployment:
  tasks:
    - export SOURCEPATH=/home/thelivin/repos/lgt-api
    - export DEPLOYPATH=/home/thelivin/app.thelivinggodtabernacle.org
    - /bin/rsync -a --delete --exclude='.git' --exclude='node_modules' --exclude='.cpanel.yml' --exclude='.env' "$SOURCEPATH"/ "$DEPLOYPATH"/
    - cd "$DEPLOYPATH" && npm ci
    - cd "$DEPLOYPATH" && npm run build
    - cd "$DEPLOYPATH" && npm prune --omit=dev
